<?xml version="1.0" encoding="UTF-8" standalone="no"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:sch="http://gear.com/test/soap" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://gear.com/test/soap" targetNamespace="http://gear.com/test/soap">
  <wsdl:types>
    <xs:schema xmlns:tns="http://spring.io/guides/gs-producing-web-service" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://gear.com/test/soap">

    <xs:element name="getTimeRequest">
        <xs:complexType>
        </xs:complexType>
    </xs:element>

    <xs:element name="getTimeResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="dateTime" type="xs:dateTime"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="getTimeRequest">
    <wsdl:part element="tns:getTimeRequest" name="getTimeRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getTimeResponse">
    <wsdl:part element="tns:getTimeResponse" name="getTimeResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="TimePort">
    <wsdl:operation name="getTime">
      <wsdl:input message="tns:getTimeRequest" name="getTimeRequest">
    </wsdl:input>
      <wsdl:output message="tns:getTimeResponse" name="getTimeResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="TimePortSoap11" type="tns:TimePort">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getTime">
      <soap:operation soapAction=""/>
      <wsdl:input name="getTimeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getTimeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TimePortService">
    <wsdl:port binding="tns:TimePortSoap11" name="TimePortSoap11">
      <soap:address location="http://localhost:8081/ws"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>